baseURL: 'https://hasaki.xyz'
languageCode: 'ZH-CN'
title: "TOM's zone"
pluralizeListTitles: false
DisqusShortname: 'hasaki-xyz'
defaultContentLanguage: 'en'
disableHugoGeneratorInject: true
copyright: "Early 2016 ~ 2019 &copy; TOM's Zone"
SectionPagesMenu: 'main'
Paginate: 24

taxonomies:
  tags: 'tags'

Params:
  # Site meta description
  description: "TOM's zone"

  webAppTitle: "TOM's zone"

  # Site's Tagline (Subtitle or Keyword)
  tagline: 'Nothing sweeter than this'

  dateFormat: 'January 2, 2006'
  colorTheme: '#ff8181'

  head404: "Sorry, I can't find what you want."
  sub404: "Back to <a href='/'>Home</a>."

  # Maximum number of item in Latest Posts or Works
  latestCount: 5
  themeAttrib: false
  # HighlightJs
  HighlightJs: true
  highlightJsStyle: 'ocean'
  HighlightJsLanguages:
    - javascript
    - python
    - go
    - css
    - swift
    - objectivec
    - rust

  # Social Links
  email: 'iamnomand@gmail.com'
  github: 'https://github.com/v-tom/'
  twitter: 'https://twitter.com/iamnomand'

  postSection: 'blog'
  workSection: 'work'
