export const Spinner = {
    SHOW_SPINNER: "SHOW_SPINNER",
    HIDE_SPINNER: "HIDE_SPINNER"
};

export const Header = {
    SET_HEADER_SCROLL_LIMIT: "SET_HEADER_SCROLL_LIMIT",
    SHOW_HEADER: "SHOW_HEADER",
    HIDE_HEADER: "HIDE_HEADER"
};

export const ReplyContainer = {};
export const ReplyBox = {};
export const ReplyList = {};

export const RouterBlog = {
    GET_ARTICLE_LIST: "GET_ARTICLE_LIST",
    LOAD_MORE: "LOAD_MORE",
    SET_TAG_NAME: "SET_TAG_NAME",
    TOGGLE_DATA_BUSY: "TOGGLE_DATA_BUSY"
};


export const RouterArticle = {
    GET_ARTICLE_DETAIL: "GET_ARTICLE_DETAIL",
    RESET_ARTICLE_DETAIL_READY: "RESET_ARTICLE_DETAIL_READY",
    SET_ARTICLE_DETAIL_READY: "SET_ARTICLE_DETAIL_READY",
    TOGGLE_ARTICLE_SIDE_BAR: "TOGGLE_ARTICLE_SIDE_BAR",
    CLEAR_ARTICLE_DETAIL_STATE: "CLEAR_ARTICLE_DETAIL_STATE"
};
