export const Header = {
  SET_HEADER_SCROLL_LIMIT: 'SET_HEADER_SCROLL_LIMIT',
  SHOW_HEADER: 'SHOW_HEADER',
  HIDE_HEADER: 'HIDE_HEADER'
}
export const RouterBlog = {
  GET_ARTICLE_LIST: 'GET_ARTICLE_LIST',
  LOAD_MORE: 'LOAD_MORE',
  SET_TAG_NAME: 'SET_TAG_NAME',
  TOGGLE_DATA_BUSY: 'TOGGLE_DATA_BUSY',
  CLEAR_BLOG_LIST_STATE: 'CLEAR_BLOG_LIST_STATE'
}


export const RouterArticle = {
  GET_ARTICLE_DETAIL: 'GET_ARTICLE_DETAIL',
  CLEAR_ARTICLE_DETAIL_STATE: 'CLEAR_ARTICLE_DETAIL_STATE'
}


export const Discuss = {
  GET_ARTICLE_REPLY: 'GET_ARTICLE_REPLY'
}

export const Me = {
  GET_MY_RESUME: 'GET_MY_RESUME'
}
