# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: First interaction
        uses: actions/first-interaction@v1.0.0
        with:
          repo-token: 213123
          issue-message: "# Message with markdown.\nThis is the message that will be displayed on users' first issue."
          pr-message: "Message that will be displayed on users' first pr. Look, a `code block` for markdown."
